apiVersion: 1
datasources:
- name: influxdb
  type: influxdb
  orgId: 1
  url: http://influxdb-service:8086
  database: telegraf
  version: 1
  editable: false
  isDefault: true
  basicAuth: true
  basicAuthUser: user
  basicAuthPassword: user
