apiVersion: v1

kind: Secret
metadata:
  name: grafana-secrets
  labels:
    app: grafana
type: Opaque
stringData:
  GF_SECURITY_ADMIN_USER: admin
  GF_SECURITY_ADMIN_PASSWORD: admin
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  labels:
    app: grafana
spec:
  selector:
    app: grafana
  type: LoadBalancer
  ports:
  - port: 3000
    name: grafana
    targetPort: 3000


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  labels:
    app: grafana
spec:
  selector:
    matchLabels:
      app: grafana
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      name: grafana-pod
      labels:
        app: grafana
    spec:
      containers:
      - image: grafana-image
        name: grafana-container
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
          name: grafana
        volumeMounts:
        - name: grafana-config
          mountPath: /etc/grafana/grafana.ini
          subPath: grafana.ini
          readOnly: true
        envFrom:
        - secretRef:
            name: grafana-secrets
      volumes:
      - name: grafana-config
        configMap:
          name: grafana-config
