apiVersion: v1
kind: Service
metadata:
  name: ftps-service
  labels:
    app: ftps
spec:
  selector:
    app: ftps
  type: LoadBalancer
  loadBalancerIP: 192.168.99.123
  ports:
  - port: 20
    name: ftp-data
    targetPort: 20
  - port: 21
    name: ftp-command
    targetPort: 21
  - port: 31000
    name: pasv
    targetPort: 31000
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ftps-pvc
  labels:
    app: ftps
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps
  labels:
    app: ftps
spec:
  selector:
    matchLabels:
      app: ftps
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      name: ftps-pod
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps-container
        image: ftps-image
        imagePullPolicy: Never
        ports:
        - containerPort: 20
          name: ftp-data
        - containerPort: 21
          name: ftp-command
        - containerPort: 31000
          name: pasv
        volumeMounts:
        - name: ftps
          mountPath: /ftp_dir
      volumes:
      - name: ftps
        persistentVolumeClaim:
          claimName: ftps-pvc
